In [30]:
import torch
import numpy as np

Tutorial na použitie pytorch

Základom pytorch je tensor, ktorý môžeme vytvárať následovne:

In [31]:
x = torch.zeros(2,2)
y = torch.rand(2,2)
z = torch.empty(2,2)
n = torch.ones(2,2)
d = torch.tensor([2.5,4,4])
print(f"{x}")
print(f"{y}")
print(f"{z}")
print(f"{n}")
print(f"{d}")

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.5802, 0.1043],
        [0.2356, 0.7495]])
tensor([[3., 0.],
        [4., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([2.5000, 4.0000, 4.0000])


Matematické operácie

In [32]:
add1 = torch.add(y,n)
sub1 = torch.sub(y,n)
mul1 = torch.mul(y,n)
div1 = torch.div(y,n)


Slicing v torch

In [33]:
x = torch.rand(5,5)
print(x[:,0])

tensor([0.6104, 0.8086, 0.6495, 0.9549, 0.4313])


Reshape funkcia v torch

In [34]:
y = x.view(25)
y = x.view(-1,5)
y

tensor([[0.6104, 0.6573, 0.6878, 0.8143, 0.7850],
        [0.8086, 0.2532, 0.6449, 0.0842, 0.8767],
        [0.6495, 0.7377, 0.6215, 0.2553, 0.4140],
        [0.9549, 0.9569, 0.0830, 0.4575, 0.9673],
        [0.4313, 0.3326, 0.4705, 0.4767, 0.4020]])

In [35]:
y.size()

torch.Size([5, 5])

Konverzia torch to np 

In [36]:
a = torch.rand(5)
b = a.numpy()
b

array([0.26722932, 0.8596515 , 0.07108212, 0.69428295, 0.00237751],
      dtype=float32)

In [37]:
c = torch.from_numpy(b)
c

tensor([0.2672, 0.8597, 0.0711, 0.6943, 0.0024])

Keď zmeníme a neskôr a máme b ktoré je konvertované z a, tak sú uložené v rovnakej pamäti, a zmení sa aj b

In [38]:
a.add_(1)

tensor([1.2672, 1.8597, 1.0711, 1.6943, 1.0024])

In [39]:
b

array([1.2672293, 1.8596516, 1.0710821, 1.694283 , 1.0023775],
      dtype=float32)

Použitie autograd v pytorch

In [40]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


Vysvetlenie pomocou numpy, bez použitia pytorch

In [3]:
import numpy as np  # Numpy je knižnica pre prácu s poľami (vektormi, maticami) a numerickými výpočtami

# Trénovacie dáta – jednoduchá lineárna závislosť
# X sú vstupné dáta (napr. 1 hodina, 2 hodiny,... práce)
# Y sú výstupy (napr. 2 €, 4 €,... odmena) → teda Y = 2 * X
X = np.array([1,2,3,4], dtype=np.float32)
Y = np.array([5,10,15,20], dtype=np.float32)

# Začiatočná hodnota váhy (parametra) w. Zatiaľ ho nastavíme na 0.
# Tento parameter sa bude počas učenia upravovať tak, aby sa znížila chyba medzi predikciou a reálnymi hodnotami.
w = 0.0


# -------------------------------------------
# FUNKCIA NA PREDIKCIU – tzv. FORWARD PASS
# -------------------------------------------
def forward(x):
    return w * x  # Predikcia: výstup modelu je jednoducho vstup * váha (w), pretože ide o lineárnu funkciu y = w * x


# -------------------------------------------
# FUNKCIA NA VÝPOČET CHYBY – tzv. LOSS
# -------------------------------------------
def loss(y, y_predicted):
    # Výpočet strednej štvorcovej chyby – Mean Squared Error (MSE)
    # (y_predicted - y) ** 2 → rozdiel medzi predikciou a skutočnosťou, na druhú (aby sme eliminovali záporné hodnoty)
    # .mean() → spriemerujeme všetky tieto chyby
    return ((y_predicted - y) ** 2).mean()


# -------------------------------------------
# FUNKCIA NA VÝPOČET GRADIENTU (Sklon chyby podľa váhy w)
# -------------------------------------------
def gradient(x, y, y_predicted):
    # Gradient určuje, ako rýchlo a ktorým smerom sa mení chyba, keď meníme parameter w.
    # Používa sa pri optimalizácii, aby sme vedeli, ako upraviť w.
    # Derivácia loss funkcie podľa w je: dL/dw = 2 * x * (y_pred - y)
    # Používame np.dot – skalárny súčin medzi x a (y_pred - y)
    # .mean() → priemerujeme hodnoty pre všetky vzorky
    return np.dot(2 * x, y_predicted - y).mean()


# -------------------------------------------
# VÝSTUP PRED ZAČIATKOM TRÉNOVANIA
# -------------------------------------------
# Skontrolujeme, čo model predikuje pred učením pre vstup x=5
# Keďže w=0, výsledok bude 0 (lebo 0 * 5 = 0)
print(f"Prediction before training: f(5) = {forward(5)}")


# -------------------------------------------
# HYPERPARAMETRE A TRÉNINGOVÁ SLUČKA
# -------------------------------------------
learning_rate = 0.01   # Určuje veľkosť kroku, ktorým sa posúvame pri aktualizácii váhy
n_iters = 20           # Počet epoch – koľkokrát prejdeme celé trénovacie dáta

# TRÉNINGOVÝ CYKLUS
for epoch in range(n_iters):
    # KROK 1: Výpočet predikcií pre všetky vstupy pomocou aktuálnej hodnoty w
    y_pred = forward(X)  # napr. ak w=2, predikcia bude [2,4,6,8]

    # KROK 2: Výpočet chyby (loss) medzi predikciou a reálnymi výstupmi
    l = loss(Y, y_pred)

    # KROK 3: Výpočet gradientu – ako veľmi sa zmení chyba, ak upravíme w
    dw = gradient(X, Y, y_pred)

    # KROK 4: Aktualizácia váhy – ideme smerom znižovania chyby (negatívny gradient)
    w -= learning_rate * dw  # gradient descent: nový w = starý w - učenie * gradient

    # KAŽDÝ 2. EPOCH VYPIŠE STAV UČENIA
    if epoch % 2 == 0:
        print(f"epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}")

# Po trénovaní bude w približne 2 (lebo skutočný vzťah bol Y = 2*X)



Prediction before training: f(5) = 0.0
epoch 1: w = 3.000, loss = 187.50000000
epoch 3: w = 4.680, loss = 4.80000210
epoch 5: w = 4.949, loss = 0.12288050
epoch 7: w = 4.992, loss = 0.00314578
epoch 9: w = 4.999, loss = 0.00008053
epoch 11: w = 5.000, loss = 0.00000206
epoch 13: w = 5.000, loss = 0.00000005
epoch 15: w = 5.000, loss = 0.00000000
epoch 17: w = 5.000, loss = 0.00000000
epoch 19: w = 5.000, loss = 0.00000000
