Filtrovanie dát

In [9]:
import numpy as np
from numpy.random import default_rng

rng = np.random.default_rng(12345)      # Stavíme v tomto prípade random
random_array = rng.normal(1,1,10)       # Vytvoríme random_array
random_array[random_array > 0]          # Vytvoríme novú maticu ale z dát, ktoré sú len viac ako 0

array([2.26372846, 0.12933826, 0.74082677, 0.92465669, 0.25911535,
       1.6488928 , 1.36105811])

In [3]:
random_array[(random_array < 0) | (random_array > 1)] #Rovná čiara sa rovná je Alt Gr + W znamená alebo

array([-0.42382504,  2.26372846, -0.3677927 ,  1.6488928 ,  1.36105811,
       -0.95286306])

In [4]:
#Môžeme to urobiť pre lepší kód takto:
mask = (random_array < 0) | (random_array > 1)
random_array[mask]

array([-0.42382504,  2.26372846, -0.3677927 ,  1.6488928 ,  1.36105811,
       -0.95286306])

Použitie na zistenie čísla delitelného 2

In [ ]:
my_array = np.arange(20)
my_array % 2 == 0               

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [14]:
my_array[my_array % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
even_odd = np.array(["Even","Odd"]*10)
even_odd != "Even"

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [ ]:
#Filtrovanie na základe iného riadku môže byť že
array1  = array1(array3 == "Hodnota")