Modifikácia dát

In [2]:
import numpy as np
from numpy.random import default_rng

In [2]:
rng = np.random.default_rng(12345)
inventory = rng.integers(1,50,10)
inventory

array([35, 12, 39, 16, 11, 40, 32, 34, 49, 20])

In [ ]:
inventory[0] = 15                                # Zmena inventára - položka 35 na pozícií [0] na 15 
inventory

array([15, 12, 39, 16, 11, 40, 32, 34, 49, 20])

In [ ]:
inventory[inventory == 15] = 25                  # Každý predmet, ktorý má hodnotu 15 zmeň ho na 25
inventory

array([25, 12, 39, 16, 11, 40, 32, 34, 49, 20])

In [4]:
my_array = np.arange(10)
my_array[my_array % 2 == 0] = 0
my_array

array([0, 1, 0, 3, 0, 5, 0, 7, 0, 9])