Vektorizácia - Proces, kde dáta prehodíme do pôvodného jazyka na ktorom stojí python - C - lepšie písanie loopov 

In [3]:
import numpy as np

In [ ]:

#Klasická python funkcia
def loop1(list1,list2):
    product_list = []
    for element1, element2 in zip(list1,list2):
        product_list.append(element1 * element2)
        return product_list

#Funckia pomocou numpy
def loop1_numpy(array1, array2):
    return array1 * array2
    
list1 = list(range(1000))
list2 = list(range(1000))

Broadcasting - dovoluje použivať vektorizáciu aj na operácie kde arrays nemajú rovnakú dĺžku

In [4]:
testarray = np.array([[1,2,3],[1,2,3],[1,2,3]])
testarray

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
testarray + 1                              #Ako to funguje? Automaticky +1 vytvorí maticu 3x3 - ktorá obsahuje 1 a doplní tieto údaje všade kde treba

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [ ]:
testarray + np.array([2,2,2])               #Ako to funguje? Máme maticu 3x3 a novu pridávame 1x3 tak ju automaticky vynásobí aby bola 3x3

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])