Začiatok tréningu

In [1]:
import numpy as np
array = np.array(range(5))
array

array([0, 1, 2, 3, 4])

In [2]:
from numpy.random import default_rng

Zadanie č.1. Prekonvertuj python list do np.array a vytvor výstup na základe size, shape, dtype, ndim (Bonus urob reshape na 10/1)

In [11]:
my_list = [x * 10 for x in range(1,11)]
my_list_update = np.array(my_list).reshape(10,1)
my_list_update

array([[ 10],
       [ 20],
       [ 30],
       [ 40],
       [ 50],
       [ 60],
       [ 70],
       [ 80],
       [ 90],
       [100]])

Koniec zadania č.1.

Vytváranie array (ones, zeros, arange, linspace, reshape)

In [16]:
np.ones(4,)

array([1., 1., 1., 1.])

In [17]:
np.zeros((2,5),dtype=int) #Ide aj float a podobne

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Importovanie Random

In [23]:
rng = default_rng(12345)
random_array = rng.random(10)
random_array # Vytvorí random číslo na základe seedu

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [24]:
#Random na základe dtdev a median
rng1 = default_rng(12345)
mean, stdev = 5,1
random_normal = rng1.normal(mean,stdev, size=10)
random_normal

array([3.57617496, 6.26372846, 4.12933826, 4.74082677, 4.92465669,
       4.25911535, 3.6322073 , 5.6488928 , 5.36105811, 3.04713694])

In [25]:
rng.integers(1,10,20) #Integers of 1 po 10 a chceme 20 hodnôt

array([7, 3, 9, 9, 7, 7, 2, 1, 3, 4, 1, 8, 5, 7, 2, 3, 2, 7, 7, 2])

In [26]:
#Lahší spôsob ako použiť random na základe medianu ak máme stálu hodnotu a nechceme ju vypisovať
rng.normal(1,15,5) #median, stdev, počet

array([ 20.83447091,  -3.49547773,  14.54379012, -23.32374101,
        -1.37283891])

Zadanie č.2 - Vytvor array na základe array1, ale prehod jeho hodnoty a následne vytvor random array 3x3 od 0 po 1 čísla

In [27]:
array1 = np.linspace(10,100,10).reshape(5,2)  #Zápis základného array
array1

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [28]:
array1.reshape(10,1)  # Transponovaná matica hodnôt

array([[ 10.],
       [ 20.],
       [ 30.],
       [ 40.],
       [ 50.],
       [ 60.],
       [ 70.],
       [ 80.],
       [ 90.],
       [100.]])

In [29]:
rng = default_rng(12345)
random_array = rng.random(9).reshape(3,3)  #random vytvára len náhodné čísla od 0 po 1 vždy
random_array

array([[0.22733602, 0.31675834, 0.79736546],
       [0.67625467, 0.39110955, 0.33281393],
       [0.59830875, 0.18673419, 0.67275604]])

Koniec zadania 3. 

Indexing a slicing array

In [30]:
product_array = np.array(["Jablko","Hruška", "Med", "Zemla","Auto"])
print(product_array[1])
print(product_array[:2])

Hruška
['Jablko' 'Hruška']


In [31]:
product_array = np.array(["Jablko","Hruška", "Med", "Zemla","Auto","Dom"])
product_array

array(['Jablko', 'Hruška', 'Med', 'Zemla', 'Auto', 'Dom'], dtype='<U6')

In [32]:
product_array_2d = np.array(["Jablko","Hruška", "Med", "Zemla","Auto","Dom"]).reshape(3,2)
product_array_2d[2,1]
product_array_2d[1,:]

array(['Med', 'Zemla'], dtype='<U6')

In [33]:
product_array_2d[-1,-1] #Posledný element

np.str_('Dom')

In [34]:
product_array[::2] #Každý druhý element berieme 

array(['Jablko', 'Med', 'Auto'], dtype='<U6')

In [35]:
product_array[:2] #Prvé 2 a usekne všetko ostatné

array(['Jablko', 'Hruška'], dtype='<U6')

In [36]:
product_array[2:] #Usekne prvé 2 a všetko ostatné nechá

array(['Med', 'Zemla', 'Auto', 'Dom'], dtype='<U6')

Zadanie číslo 4. - vytvor random array ktorý ma 9 hodnôt a vytvor z neho 3x3. potom odsekni posledný row, následne zobvraz len posledný a zobraz hodnotu 2 hodnotu v 3 riadku

In [37]:
rng = default_rng(12345)
array_random = rng.random(9).reshape(3,3)
array_random

array([[0.22733602, 0.31675834, 0.79736546],
       [0.67625467, 0.39110955, 0.33281393],
       [0.59830875, 0.18673419, 0.67275604]])

In [39]:
array[:2, :]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
array[2:, :]

In [ ]:
array[2:,1:2]

In [ ]:
array[2,1] #Alebo takto to ide tiež 

Operácie s vektorom / maticou

In [ ]:
array + 2

array([[2.22733602, 2.31675834, 2.79736546],
       [2.67625467, 2.39110955, 2.33281393],
       [2.59830875, 2.18673419, 2.67275604]])

In [ ]:
rng = np.random.default_rng(12345)
inventory = rng.integers(1,50,10)
inventory

array([35, 12, 39, 16, 11, 40, 32, 34, 49, 20])

In [ ]:
inventory/2

array([17.5,  6. , 19.5,  8. ,  5.5, 20. , 16. , 17. , 24.5, 10. ])

In [ ]:
price = (rng.random(10)*10).round(2) #Random číslo od 0 po 1, násob 10, ich počet je 10 a zaokruhli na 2
price

array([8.86, 6.97, 3.26, 7.34, 2.2 , 0.82, 1.6 , 3.4 , 4.65, 2.66])

In [ ]:
(price * inventory).sum() #Násob a daj mi finálnu hodnotu

np.float64(1143.1699999999998)

Zadanie č.5. Vytvor prices array daj mu 6 hodnôt, pripočítaj cenu +5 za poštu ku všetkému, zober array_random dosad ho pod doscount_pot

Premeň ho na jeden riadok a skráť hodnoty, pot_oved celé - 1 aby si ziskal koľko sa zaplatí celkovo a potom zisti finalnu cenu

In [ ]:
prices = np.array([5.99,6.99,22.49,99.99,4.99,49.99])
prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [ ]:
total = prices + 5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [ ]:
discount_pot = array_random[:2,:].reshape(1,6)
discount_pot

array([[0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
        0.33281393]])

In [ ]:
pot_oved = 1 - discount_pot
pot_oved

array([[0.77266398, 0.68324166, 0.20263454, 0.32374533, 0.60889045,
        0.66718607]])

In [ ]:
final_oved = total * pot_oved
final_oved.round(2)

array([[ 8.49,  8.19,  5.57, 33.99,  6.08, 36.69]])

Filtrovanie hodnôt a ich výmena

In [ ]:
rng = np.random.default_rng(12345)
sales_array = rng.random(8).reshape(2,4)
sales_array

array([[0.22733602, 0.31675834, 0.79736546, 0.67625467],
       [0.39110955, 0.33281393, 0.59830875, 0.18673419]])

In [ ]:
sales_array >= 0.25

array([[False,  True,  True,  True],
       [ True,  True,  True, False]])